### ISSUE TITLE
Failed to play

### ISSUE THREAD

**Issue by corrpel** [mancuniancol/plugin.video.rarbg#2] opened 2016-01-18 13:15 UTC
When searching in either Kickass or Rarbg, after searching for a movies and click on it you have the choise to use more versions of the movie selected. First time you click on it default "Fail to play" will be displayed before Pulsar being able to start.You need to cancel and click again in order to have it working correctly; please let me know if you need anything from me in order to solve it. thank you.

**Comment by mancuniancol** [comment] 2016-01-18 13:23
Well, it seems to the problem is with your torrent player. Try torrenter or kmediatorrent. Or wait until your torrent player is available. 
I remind you that the viewer is a shortcut between the website and your torrent player. 
If you torrent player needs time to start the viewer won't control that. 
I will close this issue, because it is not related directly with the viewer.

**Closed by mancuniancol** 2016-01-18 13:23 UTC

**Comment by corrpel** [comment] 2016-01-18 13:28
ok, thank you very much for clarifying.

**Comment by corrpel** [comment] 2016-01-18 17:30
Hi Ruben,
I receive this error before rarbg viewer starts, not before the torrent client.
I tried with different clients and on windows/rpi2 platforms, both giving the same errors. This addons are the great available for streaming from my point of view and i think people don't know about them enough :)), that's why no one reported it. So just to sum up, i am searching for a movie, select it then have the available streams. Selecting one and receiving "Playback failed, one or more ....failed to play" before the rarbgviewer window appears. I've increased the timeout playlist in advancesettings.xml, but no luck. thank you for this plugins.

**Comment by mancuniancol** [comment] 2016-01-18 18:08
If you have cancelled before. Usually, you will get an error of that type. That is between player and kodi.

**Comment by mancuniancol** [comment] 2016-01-18 18:30
I will try to do something, though. But, it is really hard from the viewer.

**Comment by mancuniancol** [comment] 2016-01-20 00:31
OK. I've found a solution. But, I am not 100% is going to work.

**Comment by corrpel** [comment] 2016-01-21 09:42
i still have the issue but it is appearing less. i am not sure how to make the dialog to go in background to avoid stopping the movie.
thanks for putting the effort

**Comment by mancuniancol** [comment] 2016-01-21 10:19
Well, the problem should fix from the player. Try another player to see which deal with better. I use torrenter and it works without any problem

**Comment by corrpel** [comment] 2016-01-22 08:13
@mancuniancol update:
I was actually the problem :)). i thought that kickass was pushed to kodi repository with 1.2.5 update but i was running 1.2.4. so the issue was on kickass script, not rarbg. so i replace the main file for kickass and now is good no more close dialog that will stop the movie. thank you and i apologies for any confusion created.
